version: "3.9"


services:

  _base: &base
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: []
    volumes:
      - .:/app
    environment: &base-environment
      ENVIRONMENT: local

  app:
    <<: *base
    ports:
      - "8000:8000"
    entrypoint: ['docker/start.sh']
